Adding input tests.

diff --git a/projdone b/projdone
--- a/projdone
+++ b/projdone
@@ -4,6 +4,55 @@
 # Purpose: mark a project DONE and move it to the completed projects
 #          directory
 
+
+# Test whether input is an org file, project directory
+# or something else.
+if [ "$1" != "" ]
+then
+    path=`realpath $1`
+    basename=`basename $path`
+
+    # Test for a path to an org file
+    if [ -f "$path" ]
+    then
+	if echo "$path" | egrep -qo ".*\.org$"
+	then
+	    echo "orgFile found: $path"
+	    orgFile=$path
+	    dirPath=`echo $path | sed "s/\/[^\/]+$//"`
+	    echo "dirPath is $dirPath"
+	    exit 0
+	else
+	    printf "Error:\n\n    Specified file is not an org-file.\n"
+	    exit 1
+	fi
+    fi
+
+    # Test for a project directory
+    if [ -d "$path" ]
+    then
+	echo "directory found"
+	basenameLower=`echo $basename | tr [:upper:] [:lower:]`".org"
+	echo "the basenameLower is $basenameLower"
+	if [ -f "$path/$basenameLower" ]
+	then
+	    echo "the input directory is a project directory"
+	    exit 0
+	else
+	    printf "Error:\n\n    Specified directory is not a project directory.\n"
+	    exit 1
+	fi
+    else
+	printf "Error:\n\n    Specified input is neither a file nor a directory.\n"
+	exit 1
+    fi
+    
+else
+    printf "Error:\n\n     No input specified.\n"
+    exit 1
+fi
+
+
 # Read in the project file path
 file=$1
 
